/**
 * WordPress dependencies
 */
import { __ } from '@wordpress/i18n';
import { applyFilters } from '@wordpress/hooks';
import {
	addCard,
	addSubmenu,
	alignCenter,
	alignJustify,
	alignLeft,
	alignNone,
	alignRight,
	archive,
	arrowDown,
	arrowLeft,
	arrowRight,
	arrowUp,
	atSymbol,
	aspectRatio,
	audio,
	backup,
	blockDefault,
	blockTable,
	border,
	box,
	brush,
	bug,
	button,
	buttons,
	calendar,
	cancelCircleFilled,
	caption,
	capturePhoto,
	captureVideo,
	category,
	chartBar,
	check,
	chevronDown,
	chevronLeft,
	chevronRight,
	chevronRightSmall,
	chevronUp,
	chevronUpDown,
	classic,
	close,
	closeSmall,
	cloudUpload,
	cloud,
	code,
	cog,
	color,
	column,
	columns,
	comment,
	commentAuthorAvatar,
	commentAuthorName,
	commentContent,
	commentEditLink,
	commentReplyLink,
	copy,
	cover,
	create,
	crop,
	currencyDollar,
	currencyEuro,
	currencyPound,
	customPostType,
	desktop,
	dragHandle,
	drawerLeft,
	drawerRight,
	download,
	edit,
	external,
	file,
	filter,
	flipHorizontal,
	flipVertical,
	formatBold,
	formatCapitalize,
	formatIndent,
	formatIndentRTL,
	formatItalic,
	formatListBullets,
	formatListBulletsRTL,
	formatListNumbered,
	formatListNumberedRTL,
	formatLtr,
	formatLowercase,
	formatOutdent,
	formatOutdentRTL,
	formatRtl,
	formatStrikethrough,
	formatUnderline,
	formatUppercase,
	fullscreen,
	gallery,
	globe,
	grid,
	group,
	handle,
	heading,
	help,
	helpFilled,
	inbox,
	institution,
	home,
	html,
	image,
	info,
	insertAfter,
	insertBefore,
	justifyLeft,
	justifyCenter,
	justifyRight,
	justifySpaceBetween,
	justifyStretch,
	key,
	keyboardClose,
	keyboardReturn,
	layout,
	lifesaver,
	lineDashed,
	lineDotted,
	lineSolid,
	link,
	linkOff,
	list,
	listItem,
	listView,
	lock,
	lockOutline,
	lockSmall,
	login,
	loop,
	mapMarker,
	media,
	mediaAndText,
	megaphone,
	menu,
	mobile,
	more,
	moreHorizontal,
	moreHorizontalMobile,
	moreVertical,
	moveTo,
	navigation,
	overlayText,
	pageBreak,
	customLink,
	page,
	pages,
	paragraph,
	payment,
	percent,
	positionCenter,
	positionLeft,
	positionRight,
	pencil,
	people,
	pin,
	plugins,
	plusCircleFilled,
	plusCircle,
	plus,
	post,
	postAuthor,
	postCategories,
	postContent,
	postComments,
	postCommentsCount,
	postCommentsForm,
	postDate,
	postExcerpt,
	postFeaturedImage,
	postList,
	postTerms,
	previous,
	next,
	preformatted,
	pullLeft,
	pullRight,
	pullquote,
	queryPagination,
	queryPaginationNext,
	queryPaginationNumbers,
	queryPaginationPrevious,
	quote,
	receipt,
	redo,
	removeBug,
	removeSubmenu,
	replace,
	reset,
	resizeCornerNE,
	reusableBlock,
	rotateLeft,
	rotateRight,
	row,
	rss,
	search,
	seen,
	separator,
	settings,
	shadow,
	share,
	shield,
	shortcode,
	shuffle,
	siteLogo,
	stack,
	starEmpty,
	starFilled,
	starHalf,
	store,
	stretchFullWidth,
	styles,
	shipping,
	stretchWide,
	subscript,
	superscript,
	swatch,
	symbol,
	symbolFilled,
	tableColumnAfter,
	tableColumnBefore,
	tableColumnDelete,
	tableRowAfter,
	tableRowBefore,
	tableRowDelete,
	table,
	tag,
	termDescription,
	footer,
	header,
	sidebar,
	textColor,
	tablet,
	tip,
	title,
	tool,
	trash,
	trendingDown,
	trendingUp,
	typography,
	undo,
	ungroup,
	unlock,
	unseen,
	update,
	upload,
	verse,
	video,
	warning,
	widget,
} from '@wordpress/icons';

/**
 * Internal dependencies
 */
import {
	amazon,
	bandcamp,
	behance,
	chain,
	codepen,
	deviantart,
	dribbble,
	dropbox,
	etsy,
	facebook,
	feed,
	fivehundredpx,
	flickr,
	foursquare,
	goodreads,
	google,
	github,
	instagram,
	lastfm,
	linkedin,
	mail,
	mastodon,
	meetup,
	medium,
	patreon,
	pinterest,
	pocket,
	redditSolid,
	reddit,
	skype,
	snapchat,
	soundcloud,
	spotify,
	telegram,
	threads,
	tiktok,
	tumblr,
	twitch,
	twitter,
	vimeo,
	vk,
	whatsapp,
	wordpress,
	x,
	yelp,
	youtube,
} from './wordpress/social';

// Temporary icon specifications that are not yet in the NPM package.
import { sparkles } from './wordpress/temp';

const wordpressSocialIcons = [
	{
		isDefault: true,
		name: 'wordpress',
		title: 'WordPress',
		icon: wordpress,
		categories: [ 'logos' ],
	},
	{
		name: 'fivehundredpx',
		title: '500px',
		icon: fivehundredpx,
		categories: [ 'logos' ],
	},
	{
		name: 'amazon',
		title: 'Amazon',
		icon: amazon,
		categories: [ 'logos' ],
	},
	{
		name: 'bandcamp',
		title: 'Bandcamp',
		icon: bandcamp,
		categories: [ 'logos' ],
	},
	{
		name: 'behance',
		title: 'Behance',
		icon: behance,
		categories: [ 'logos' ],
	},
	{
		name: 'chain',
		title: 'Link',
		icon: chain,
	},
	{
		name: 'codepen',
		title: 'CodePen',
		icon: codepen,
		categories: [ 'logos' ],
	},
	{
		name: 'deviantart',
		title: 'DeviantArt',
		icon: deviantart,
		categories: [ 'logos' ],
	},
	{
		name: 'dribbble',
		title: 'Dribbble',
		icon: dribbble,
		categories: [ 'logos' ],
	},
	{
		name: 'dropbox',
		title: 'Dropbox',
		icon: dropbox,
		categories: [ 'logos' ],
	},
	{
		name: 'etsy',
		title: 'Etsy',
		icon: etsy,
		categories: [ 'logos' ],
	},
	{
		name: 'facebook',
		title: 'Facebook',
		icon: facebook,
		categories: [ 'logos' ],
	},
	{
		name: 'feed',
		title: 'RSS Feed',
		icon: feed,
		categories: [ 'logos' ],
	},
	{
		name: 'flickr',
		title: 'Flickr',
		icon: flickr,
		categories: [ 'logos' ],
	},
	{
		name: 'foursquare',
		title: 'Foursquare',
		icon: foursquare,
		categories: [ 'logos' ],
	},
	{
		name: 'goodreads',
		title: 'Goodreads',
		icon: goodreads,
		categories: [ 'logos' ],
	},
	{
		name: 'google',
		title: 'Google',
		icon: google,
		categories: [ 'logos' ],
	},
	{
		name: 'github',
		title: 'GitHub',
		icon: github,
		categories: [ 'logos' ],
	},
	{
		name: 'instagram',
		title: 'Instagram',
		icon: instagram,
		categories: [ 'logos' ],
	},
	{
		name: 'lastfm',
		title: 'Last.fm',
		icon: lastfm,
		categories: [ 'logos' ],
	},
	{
		name: 'linkedin',
		title: 'LinkedIn',
		icon: linkedin,
		categories: [ 'logos' ],
	},
	{
		name: 'mail',
		title: 'Mail',
		keywords: [ 'email', 'e-mail' ],
		icon: mail,
	},
	{
		name: 'mastodon',
		title: 'Mastodon',
		icon: mastodon,
		categories: [ 'logos' ],
	},
	{
		name: 'meetup',
		title: 'Meetup',
		icon: meetup,
		categories: [ 'logos' ],
	},
	{
		name: 'medium',
		title: 'Medium',
		icon: medium,
		categories: [ 'logos' ],
	},
	{
		name: 'patreon',
		title: 'Patreon',
		icon: patreon,
		categories: [ 'logos' ],
	},
	{
		name: 'pinterest',
		title: 'Pinterest',
		icon: pinterest,
		categories: [ 'logos' ],
	},
	{
		name: 'pocket',
		title: 'Pocket',
		icon: pocket,
		categories: [ 'logos' ],
	},
	{
		name: 'reddit-solid',
		title: 'Reddit Solid',
		icon: redditSolid,
		categories: [ 'logos' ],
	},
	{
		name: 'reddit',
		title: 'Reddit',
		icon: reddit,
		categories: [ 'logos' ],
	},
	{
		name: 'skype',
		title: 'Skype',
		icon: skype,
		categories: [ 'logos' ],
	},
	{
		name: 'snapchat',
		title: 'Snapchat',
		icon: snapchat,
		categories: [ 'logos' ],
	},
	{
		name: 'soundcloud',
		title: 'SoundCloud',
		icon: soundcloud,
		categories: [ 'logos' ],
	},
	{
		name: 'spotify',
		title: 'Spotify',
		icon: spotify,
		categories: [ 'logos' ],
	},
	{
		name: 'telegram',
		title: 'Telegram',
		icon: telegram,
		categories: [ 'logos' ],
	},
	{
		name: 'threads',
		title: 'Threads',
		icon: threads,
		categories: [ 'logos' ],
	},
	{
		name: 'tiktok',
		title: 'TikTok',
		icon: tiktok,
		categories: [ 'logos' ],
	},
	{
		name: 'tumblr',
		title: 'Tumblr',
		icon: tumblr,
		categories: [ 'logos' ],
	},
	{
		name: 'twitch',
		title: 'Twitch',
		icon: twitch,
		categories: [ 'logos' ],
	},
	{
		isDefault: true,
		name: 'twitter',
		title: 'Twitter',
		icon: twitter,
		categories: [ 'logos' ],
	},
	{
		name: 'vimeo',
		title: 'Vimeo',
		icon: vimeo,
		categories: [ 'logos' ],
	},
	{
		name: 'vk',
		title: 'VK',
		icon: vk,
		categories: [ 'logos' ],
	},
	{
		name: 'whatsapp',
		title: 'WhatsApp',
		icon: whatsapp,
		categories: [ 'logos' ],
	},
	{
		name: 'x',
		title: 'X',
		icon: x,
		categories: [ 'logos' ],
		keywords: [ 'twitter' ],
	},
	{
		name: 'yelp',
		title: 'Yelp',
		icon: yelp,
		categories: [ 'logos' ],
	},
	{
		name: 'youtube',
		title: 'YouTube',
		icon: youtube,
		categories: [ 'logos' ],
	},
];

const wordpressIcons = [
	{
		name: 'addCard',
		title: __( 'Add Card', 'enable-navigation-icons' ),
		icon: addCard,
	},
	{
		name: 'addSubmenu',
		title: __( 'Add Submenu', 'enable-navigation-icons' ),
		icon: addSubmenu,
		categories: [ 'arrows' ],
	},
	{
		name: 'alignCenter',
		title: __( 'Align Center', 'enable-navigation-icons' ),
		icon: alignCenter,
		categories: [ 'editor' ],
	},
	{
		name: 'alignJustify',
		title: __( 'Align Justify', 'enable-navigation-icons' ),
		icon: alignJustify,
		categories: [ 'editor' ],
	},
	{
		name: 'alignLeft',
		title: __( 'Align Left', 'enable-navigation-icons' ),
		icon: alignLeft,
		categories: [ 'editor' ],
	},
	{
		name: 'alignNone',
		title: __( 'Align None', 'enable-navigation-icons' ),
		icon: alignNone,
		categories: [ 'editor' ],
	},
	{
		name: 'alignRight',
		title: __( 'Align Right', 'enable-navigation-icons' ),
		icon: alignRight,
		categories: [ 'editor' ],
	},
	{
		name: 'archive',
		title: __( 'Archive', 'enable-navigation-icons' ),
		icon: archive,
		categories: [ 'blocks' ],
	},
	{
		name: 'arrowDown',
		title: __( 'Arrow Down', 'enable-navigation-icons' ),
		icon: arrowDown,
		categories: [ 'arrows' ],
	},
	{
		name: 'arrowLeft',
		title: __( 'Arrow Left', 'enable-navigation-icons' ),
		icon: arrowLeft,
		categories: [ 'arrows' ],
	},
	{
		name: 'arrowRight',
		title: __( 'Arrow Right', 'enable-navigation-icons' ),
		icon: arrowRight,
		categories: [ 'arrows' ],
	},
	{
		name: 'arrowUp',
		title: __( 'Arrow Up', 'enable-navigation-icons' ),
		icon: arrowUp,
		categories: [ 'arrows' ],
	},
	{
		name: 'atSymbol',
		title: __( 'At Symbol', 'enable-navigation-icons' ),
		icon: atSymbol,
	},
	{
		name: 'aspectRatio',
		title: __( 'Aspect Ratio', 'enable-navigation-icons' ),
		icon: aspectRatio,
		categories: [ 'media' ],
	},
	{
		name: 'audio',
		title: __( 'Audio', 'enable-navigation-icons' ),
		icon: audio,
		categories: [ 'media' ],
	},
	{
		name: 'backup',
		title: __( 'Backup', 'enable-navigation-icons' ),
		icon: backup,
	},
	{
		name: 'blockDefault',
		title: __( 'Block Default', 'enable-navigation-icons' ),
		icon: blockDefault,
		categories: [ 'blocks' ],
	},
	{
		name: 'blockTable',
		title: __( 'Block Table', 'enable-navigation-icons' ),
		icon: blockTable,
	},
	{
		name: 'border',
		title: __( 'Border', 'enable-navigation-icons' ),
		icon: border,
	},
	{
		name: 'box',
		title: __( 'Box', 'enable-navigation-icons' ),
		icon: box,
	},
	{
		name: 'brush',
		title: __( 'Brush', 'enable-navigation-icons' ),
		icon: brush,
	},
	{
		name: 'bug',
		title: __( 'Bug', 'enable-navigation-icons' ),
		icon: bug,
	},
	{
		name: 'button',
		title: __( 'Button', 'enable-navigation-icons' ),
		icon: button,
		categories: [ 'blocks' ],
	},
	{
		name: 'buttons',
		title: __( 'Buttons', 'enable-navigation-icons' ),
		icon: buttons,
		categories: [ 'blocks' ],
	},
	{
		name: 'calendar',
		title: __( 'Calendar', 'enable-navigation-icons' ),
		icon: calendar,
		categories: [ 'blocks' ],
	},
	{
		name: 'cancelCircleFilled',
		title: __( 'Cancel - Circle Filled', 'enable-navigation-icons' ),
		icon: cancelCircleFilled,
	},
	{
		name: 'caption',
		title: __( 'Caption', 'enable-navigation-icons' ),
		icon: caption,
	},
	{
		name: 'capturePhoto',
		title: __( 'Capture Photo', 'enable-navigation-icons' ),
		icon: capturePhoto,
		categories: [ 'media' ],
	},
	{
		name: 'captureVideo',
		title: __( 'Capture Video', 'enable-navigation-icons' ),
		icon: captureVideo,
		categories: [ 'media' ],
	},
	{
		name: 'category',
		title: __( 'Category', 'enable-navigation-icons' ),
		icon: category,
		categories: [ 'blocks' ],
	},
	{
		name: 'chartBar',
		title: __( 'Chart Bar', 'enable-navigation-icons' ),
		icon: chartBar,
	},
	{
		name: 'check',
		title: __( 'Check', 'enable-navigation-icons' ),
		icon: check,
	},
	{
		name: 'chevronDown',
		title: __( 'Chevron Down', 'enable-navigation-icons' ),
		icon: chevronDown,
		categories: [ 'arrows' ],
	},
	{
		name: 'chevronLeft',
		title: __( 'Chevron Left', 'enable-navigation-icons' ),
		icon: chevronLeft,
		categories: [ 'arrows' ],
	},
	{
		name: 'chevronRight',
		title: __( 'Chevron Right', 'enable-navigation-icons' ),
		icon: chevronRight,
		categories: [ 'arrows' ],
	},
	{
		name: 'chevronRightSmall',
		title: __( 'Chevron Right - Small', 'enable-navigation-icons' ),
		icon: chevronRightSmall,
		categories: [ 'arrows' ],
	},
	{
		name: 'chevronUp',
		title: __( 'Chevron Up', 'enable-navigation-icons' ),
		icon: chevronUp,
		categories: [ 'arrows' ],
	},
	{
		name: 'chevronUpDown',
		title: __( 'Chevron Up/Down', 'enable-navigation-icons' ),
		icon: chevronUpDown,
		categories: [ 'arrows' ],
	},
	{
		name: 'classic',
		title: __( 'Classic', 'enable-navigation-icons' ),
		icon: classic,
		categories: [ 'blocks' ],
	},
	{
		name: 'close',
		title: __( 'Close', 'enable-navigation-icons' ),
		icon: close,
	},
	{
		name: 'closeSmall',
		title: __( 'Close - Small', 'enable-navigation-icons' ),
		icon: closeSmall,
	},
	{
		name: 'cloudUpload',
		title: __( 'Cloud Upload', 'enable-navigation-icons' ),
		icon: cloudUpload,
		categories: [ 'arrows' ],
	},
	{
		name: 'cloud',
		title: __( 'Cloud', 'enable-navigation-icons' ),
		icon: cloud,
	},
	{
		name: 'code',
		title: __( 'Code', 'enable-navigation-icons' ),
		icon: code,
		categories: [ 'blocks' ],
	},
	{
		name: 'cog',
		title: __( 'Cog', 'enable-navigation-icons' ),
		icon: cog,
	},
	{
		name: 'color',
		title: __( 'Color', 'enable-navigation-icons' ),
		icon: color,
	},
	{
		name: 'column',
		title: __( 'Column', 'enable-navigation-icons' ),
		icon: column,
		categories: [ 'blocks' ],
	},
	{
		name: 'columns',
		title: __( 'Columns', 'enable-navigation-icons' ),
		icon: columns,
		categories: [ 'blocks' ],
	},
	{
		name: 'comment',
		title: __( 'Comment', 'enable-navigation-icons' ),
		icon: comment,
		categories: [ 'blocks' ],
	},
	{
		name: 'commentAuthorAvatar',
		title: __( 'Comment Author Avatar', 'enable-navigation-icons' ),
		icon: commentAuthorAvatar,
		categories: [ 'blocks' ],
	},
	{
		name: 'commentAuthorName',
		title: __( 'Comment Author Name', 'enable-navigation-icons' ),
		icon: commentAuthorName,
		categories: [ 'blocks' ],
	},
	{
		name: 'commentContent',
		title: __( 'Comment Content', 'enable-navigation-icons' ),
		icon: commentContent,
		categories: [ 'blocks' ],
	},
	{
		name: 'commentEditLink',
		title: __( 'Comment Edit Link', 'enable-navigation-icons' ),
		icon: commentEditLink,
		categories: [ 'blocks' ],
	},
	{
		name: 'commentReplyLink',
		title: __( 'Comment Reply Link', 'enable-navigation-icons' ),
		icon: commentReplyLink,
		categories: [ 'blocks' ],
	},
	{
		name: 'copy',
		title: __( 'Copy', 'enable-navigation-icons' ),
		icon: copy,
	},
	{
		name: 'cover',
		title: __( 'Cover', 'enable-navigation-icons' ),
		icon: cover,
		categories: [ 'blocks' ],
	},
	{
		name: 'create',
		title: __( 'Create', 'enable-navigation-icons' ),
		icon: create,
	},
	{
		name: 'crop',
		title: __( 'Crop', 'enable-navigation-icons' ),
		icon: crop,
	},
	{
		name: 'currencyDollar',
		title: __( 'Currency Dollar', 'enable-navigation-icons' ),
		icon: currencyDollar,
	},
	{
		name: 'currencyEuro',
		title: __( 'Currency Euro', 'enable-navigation-icons' ),
		icon: currencyEuro,
	},
	{
		name: 'currencyPound',
		title: __( 'Currency Pound', 'enable-navigation-icons' ),
		icon: currencyPound,
	},
	{
		name: 'customPostType',
		title: __( 'Custom Post Type', 'enable-navigation-icons' ),
		icon: customPostType,
	},
	{
		name: 'desktop',
		title: __( 'Desktop', 'enable-navigation-icons' ),
		icon: desktop,
		categories: [ 'devices' ],
	},
	{
		name: 'dragHandle',
		title: __( 'Drag Handle', 'enable-navigation-icons' ),
		icon: dragHandle,
	},
	{
		name: 'drawerLeft',
		title: __( 'Drawer Left', 'enable-navigation-icons' ),
		icon: drawerLeft,
		keywords: [ 'column' ],
	},
	{
		name: 'drawerRight',
		title: __( 'Drawer Right', 'enable-navigation-icons' ),
		icon: drawerRight,
		keywords: [ 'column' ],
	},
	{
		name: 'download',
		title: __( 'Download', 'enable-navigation-icons' ),
		icon: download,
		categories: [ 'arrows' ],
	},
	{
		name: 'edit',
		title: __( 'Edit', 'enable-navigation-icons' ),
		icon: edit,
	},
	{
		name: 'external',
		title: __( 'External', 'enable-navigation-icons' ),
		icon: external,
	},
	{
		name: 'file',
		title: __( 'File', 'enable-navigation-icons' ),
		icon: file,
	},
	{
		name: 'filter',
		title: __( 'Filter', 'enable-navigation-icons' ),
		icon: filter,
		keywords: [ 'triangle' ],
	},
	{
		name: 'flipHorizontal',
		title: __( 'Flip Horizontal', 'enable-navigation-icons' ),
		icon: flipHorizontal,
	},
	{
		name: 'flipVertical',
		title: __( 'Flip Vertical', 'enable-navigation-icons' ),
		icon: flipVertical,
	},
	{
		name: 'formatBold',
		title: __( 'Format Bold', 'enable-navigation-icons' ),
		icon: formatBold,
		categories: [ 'editor' ],
	},
	{
		name: 'formatCapitalize',
		title: __( 'Format Capitalize', 'enable-navigation-icons' ),
		icon: formatCapitalize,
		categories: [ 'editor' ],
	},
	{
		name: 'formatIndent',
		title: __( 'Format Indent', 'enable-navigation-icons' ),
		icon: formatIndent,
		categories: [ 'editor' ],
	},
	{
		name: 'formatIndentRTL',
		title: __( 'Format Indent RTL', 'enable-navigation-icons' ),
		icon: formatIndentRTL,
	},
	{
		name: 'formatItalic',
		title: __( 'Format Italic', 'enable-navigation-icons' ),
		icon: formatItalic,
		categories: [ 'editor' ],
	},
	{
		name: 'formatListBullets',
		title: __( 'Format List Bullets', 'enable-navigation-icons' ),
		icon: formatListBullets,
		categories: [ 'editor' ],
	},
	{
		name: 'formatListBulletsRTL',
		title: __( 'Format List Bullets RTL', 'enable-navigation-icons' ),
		icon: formatListBulletsRTL,
		categories: [ 'editor' ],
	},
	{
		name: 'formatListNumbered',
		title: __( 'Format List Numbered', 'enable-navigation-icons' ),
		icon: formatListNumbered,
		categories: [ 'editor' ],
	},
	{
		name: 'formatListNumberedRTL',
		title: __( 'Format List Numbered RTL', 'enable-navigation-icons' ),
		icon: formatListNumberedRTL,
		categories: [ 'editor' ],
	},
	{
		name: 'formatLtr',
		title: __( 'Format LTR', 'enable-navigation-icons' ),
		icon: formatLtr,
		categories: [ 'editor' ],
	},
	{
		name: 'formatLowercase',
		title: __( 'Format Lowercase', 'enable-navigation-icons' ),
		icon: formatLowercase,
		categories: [ 'editor' ],
	},
	{
		name: 'formatOutdent',
		title: __( 'Format Outdent', 'enable-navigation-icons' ),
		icon: formatOutdent,
		categories: [ 'editor' ],
	},
	{
		name: 'formatOutdentRTL',
		title: __( 'Format Outdent RTL', 'enable-navigation-icons' ),
		icon: formatOutdentRTL,
		categories: [ 'editor' ],
	},
	{
		name: 'formatRtl',
		title: __( 'Format RTL', 'enable-navigation-icons' ),
		icon: formatRtl,
		categories: [ 'editor' ],
	},
	{
		name: 'formatStrikethrough',
		title: __( 'Format Strikethrough', 'enable-navigation-icons' ),
		icon: formatStrikethrough,
		categories: [ 'editor' ],
	},
	{
		name: 'formatUnderline',
		title: __( 'Format Underline', 'enable-navigation-icons' ),
		icon: formatUnderline,
		categories: [ 'editor' ],
	},
	{
		name: 'formatUppercase',
		title: __( 'Format Uppercase', 'enable-navigation-icons' ),
		icon: formatUppercase,
		categories: [ 'editor' ],
	},
	{
		name: 'fullscreen',
		title: __( 'Fullscreen', 'enable-navigation-icons' ),
		icon: fullscreen,
		categories: [ 'editor' ],
	},
	{
		name: 'gallery',
		title: __( 'Gallery', 'enable-navigation-icons' ),
		icon: gallery,
		categories: [ 'blocks', 'media' ],
	},
	{
		name: 'globe',
		title: __( 'Globe', 'enable-navigation-icons' ),
		icon: globe,
	},
	{
		name: 'grid',
		title: __( 'Grid', 'enable-navigation-icons' ),
		icon: grid,
	},
	{
		name: 'group',
		title: __( 'Group', 'enable-navigation-icons' ),
		icon: group,
		categories: [ 'blocks' ],
	},
	{
		name: 'handle',
		title: __( 'Handle', 'enable-navigation-icons' ),
		icon: handle,
	},
	{
		name: 'heading',
		title: __( 'Heading', 'enable-navigation-icons' ),
		icon: heading,
		categories: [ 'blocks' ],
	},
	{
		name: 'help',
		title: __( 'Help', 'enable-navigation-icons' ),
		icon: help,
	},
	{
		name: 'helpFilled',
		title: __( 'Help - Filled', 'enable-navigation-icons' ),
		icon: helpFilled,
	},
	{
		name: 'inbox',
		title: __( 'Inbox', 'enable-navigation-icons' ),
		icon: inbox,
	},
	{
		name: 'institution',
		title: __( 'Institution', 'enable-navigation-icons' ),
		icon: institution,
	},
	{
		name: 'home',
		title: __( 'Home', 'enable-navigation-icons' ),
		icon: home,
		categories: [ 'blocks' ],
	},
	{
		name: 'html',
		title: __( 'HTML', 'enable-navigation-icons' ),
		icon: html,
		categories: [ 'blocks' ],
	},
	{
		isDefault: true,
		name: 'image',
		title: __( 'Image', 'enable-navigation-icons' ),
		icon: image,
		categories: [ 'blocks', 'media' ],
	},
	{
		name: 'info',
		title: __( 'Info', 'enable-navigation-icons' ),
		icon: info,
	},
	{
		name: 'insertAfter',
		title: __( 'Insert After', 'enable-navigation-icons' ),
		icon: insertAfter,
		categories: [ 'editor' ],
	},
	{
		name: 'insertBefore',
		title: __( 'Insert Before', 'enable-navigation-icons' ),
		icon: insertBefore,
		categories: [ 'editor' ],
	},
	{
		name: 'justifyLeft',
		title: __( 'Justify Left', 'enable-navigation-icons' ),
		icon: justifyLeft,
		categories: [ 'editor' ],
	},
	{
		name: 'justifyCenter',
		title: __( 'Justify Center', 'enable-navigation-icons' ),
		icon: justifyCenter,
		categories: [ 'editor' ],
	},
	{
		name: 'justifyRight',
		title: __( 'Justify Right', 'enable-navigation-icons' ),
		icon: justifyRight,
		categories: [ 'editor' ],
	},
	{
		name: 'justifySpaceBetween',
		title: __( 'Justify Space Between', 'enable-navigation-icons' ),
		icon: justifySpaceBetween,
		categories: [ 'editor' ],
	},
	{
		name: 'justifyStretch',
		title: __( 'Justify Stretch', 'enable-navigation-icons' ),
		icon: justifyStretch,
		categories: [ 'editor' ],
	},
	{
		name: 'key',
		title: __( 'Key', 'enable-navigation-icons' ),
		icon: key,
	},
	{
		name: 'keyboardClose',
		title: __( 'Keyboard Close', 'enable-navigation-icons' ),
		icon: keyboardClose,
		categories: [ 'editor' ],
	},
	{
		name: 'keyboardReturn',
		title: __( 'Keyboard Return', 'enable-navigation-icons' ),
		icon: keyboardReturn,
		categories: [ 'editor' ],
	},
	{
		name: 'layout',
		title: __( 'Layout', 'enable-navigation-icons' ),
		icon: layout,
	},
	{
		name: 'lifesaver',
		title: __( 'Lifesaver', 'enable-navigation-icons' ),
		icon: lifesaver,
	},
	{
		name: 'lineDashed',
		title: __( 'Line Dashed', 'enable-navigation-icons' ),
		icon: lineDashed,
	},
	{
		name: 'lineDotted',
		title: __( 'Line Dotted', 'enable-navigation-icons' ),
		icon: lineDotted,
	},
	{
		name: 'lineSolid',
		title: __( 'Line Solid', 'enable-navigation-icons' ),
		icon: lineSolid,
	},
	{
		name: 'link',
		title: __( 'Link', 'enable-navigation-icons' ),
		icon: link,
		categories: [ 'editor' ],
	},
	{
		name: 'linkOff',
		title: __( 'Link Off', 'enable-navigation-icons' ),
		icon: linkOff,
		categories: [ 'editor' ],
	},
	{
		name: 'list',
		title: __( 'List', 'enable-navigation-icons' ),
		icon: list,
		categories: [ 'blocks' ],
	},
	{
		name: 'listItem',
		title: __( 'List Item', 'enable-navigation-icons' ),
		icon: listItem,
		categories: [ 'blocks' ],
	},
	{
		name: 'listView',
		title: __( 'List View', 'enable-navigation-icons' ),
		icon: listView,
		categories: [ 'editor' ],
	},
	{
		name: 'lock',
		title: __( 'Lock', 'enable-navigation-icons' ),
		icon: lock,
		categories: [ 'editor' ],
	},
	{
		name: 'lockOutline',
		title: __( 'Lock Outline', 'enable-navigation-icons' ),
		icon: lockOutline,
		categories: [ 'editor' ],
	},
	{
		name: 'lockSmall',
		title: __( 'Lock Small', 'enable-navigation-icons' ),
		icon: lockSmall,
		categories: [ 'editor' ],
	},
	{
		name: 'login',
		title: __( 'Login', 'enable-navigation-icons' ),
		icon: login,
	},
	{
		name: 'loop',
		title: __( 'Loop', 'enable-navigation-icons' ),
		icon: loop,
		categories: [ 'blocks' ],
	},
	{
		name: 'mapMarker',
		title: __( 'Map Marker', 'enable-navigation-icons' ),
		icon: mapMarker,
	},
	{
		name: 'media',
		title: __( 'Media', 'enable-navigation-icons' ),
		icon: media,
		categories: [ 'blocks', 'media' ],
	},
	{
		name: 'mediaAndText',
		title: __( 'Media & Text', 'enable-navigation-icons' ),
		icon: mediaAndText,
		categories: [ 'blocks', 'media' ],
	},
	{
		name: 'megaphone',
		title: __( 'Megaphone', 'enable-navigation-icons' ),
		icon: megaphone,
	},
	{
		name: 'menu',
		title: __( 'Menu', 'enable-navigation-icons' ),
		icon: menu,
	},
	{
		name: 'mobile',
		title: __( 'Mobile', 'enable-navigation-icons' ),
		icon: mobile,
		categories: [ 'devices' ],
	},
	{
		name: 'more',
		title: __( 'More', 'enable-navigation-icons' ),
		icon: more,
	},
	{
		name: 'moreHorizontal',
		title: __( 'More Horizontal', 'enable-navigation-icons' ),
		icon: moreHorizontal,
	},
	{
		name: 'moreHorizontalMobile',
		title: __( 'More Horizontal - Mobile', 'enable-navigation-icons' ),
		icon: moreHorizontalMobile,
	},
	{
		name: 'moreVertical',
		title: __( 'More Vertical', 'enable-navigation-icons' ),
		icon: moreVertical,
	},
	{
		name: 'moveTo',
		title: __( 'Move To', 'enable-navigation-icons' ),
		icon: moveTo,
		categories: [ 'arrows' ],
	},
	{
		name: 'navigation',
		title: __( 'Navigation', 'enable-navigation-icons' ),
		icon: navigation,
	},
	{
		name: 'overlayText',
		title: __( 'Overlay Text', 'enable-navigation-icons' ),
		icon: overlayText,
	},
	{
		name: 'pageBreak',
		title: __( 'Page Break', 'enable-navigation-icons' ),
		icon: pageBreak,
	},
	{
		name: 'customLink',
		title: __( 'Custom Link', 'enable-navigation-icons' ),
		icon: customLink,
	},
	{
		name: 'page',
		title: __( 'Page', 'enable-navigation-icons' ),
		icon: page,
	},
	{
		name: 'pages',
		title: __( 'Pages', 'enable-navigation-icons' ),
		icon: pages,
	},
	{
		name: 'paragraph',
		title: __( 'Paragraph', 'enable-navigation-icons' ),
		icon: paragraph,
	},
	{
		name: 'payment',
		title: __( 'Payment', 'enable-navigation-icons' ),
		icon: payment,
	},
	{
		name: 'percent',
		title: __( 'Percent', 'enable-navigation-icons' ),
		icon: percent,
	},
	{
		name: 'positionCenter',
		title: __( 'Position Center', 'enable-navigation-icons' ),
		icon: positionCenter,
	},
	{
		name: 'positionLeft',
		title: __( 'Position Left', 'enable-navigation-icons' ),
		icon: positionLeft,
	},
	{
		name: 'positionRight',
		title: __( 'Position Right', 'enable-navigation-icons' ),
		icon: positionRight,
	},
	{
		name: 'post',
		title: __( 'Post', 'enable-navigation-icons' ),
		icon: post,
	},
	{
		name: 'pencil',
		title: __( 'Pencil', 'enable-navigation-icons' ),
		icon: pencil,
	},
	{
		name: 'people',
		title: __( 'People', 'enable-navigation-icons' ),
		icon: people,
	},
	{
		name: 'pin',
		title: __( 'Pin', 'enable-navigation-icons' ),
		icon: pin,
	},
	{
		name: 'plugins',
		title: __( 'Plugins', 'enable-navigation-icons' ),
		icon: plugins,
	},
	{
		name: 'plusCircleFilled',
		title: __( 'Plus Circle - Filled', 'enable-navigation-icons' ),
		icon: plusCircleFilled,
	},
	{
		name: 'plusCircle',
		title: __( 'Plus Circle', 'enable-navigation-icons' ),
		icon: plusCircle,
	},
	{
		name: 'plus',
		title: __( 'Plus', 'enable-navigation-icons' ),
		icon: plus,
	},
	{
		name: 'postAuthor',
		title: __( 'Post Author', 'enable-navigation-icons' ),
		icon: postAuthor,
		categories: [ 'blocks' ],
	},
	{
		name: 'postCategories',
		title: __( 'Post Categories', 'enable-navigation-icons' ),
		icon: postCategories,
		categories: [ 'blocks' ],
	},
	{
		name: 'postContent',
		title: __( 'Post Content', 'enable-navigation-icons' ),
		icon: postContent,
		categories: [ 'blocks' ],
	},
	{
		name: 'postComments',
		title: __( 'Post Comments', 'enable-navigation-icons' ),
		icon: postComments,
		categories: [ 'blocks' ],
	},
	{
		name: 'postCommentsCount',
		title: __( 'Post Comment Count', 'enable-navigation-icons' ),
		icon: postCommentsCount,
	},
	{
		name: 'postCommentsForm',
		title: __( 'Post Comments Form', 'enable-navigation-icons' ),
		icon: postCommentsForm,
		categories: [ 'blocks' ],
	},
	{
		name: 'postDate',
		title: __( 'Post Date', 'enable-navigation-icons' ),
		icon: postDate,
		categories: [ 'blocks' ],
	},
	{
		name: 'postExcerpt',
		title: __( 'Post Excerpt', 'enable-navigation-icons' ),
		icon: postExcerpt,
		categories: [ 'blocks' ],
	},
	{
		name: 'postFeaturedImage',
		title: __( 'Post Featured Image', 'enable-navigation-icons' ),
		icon: postFeaturedImage,
		categories: [ 'blocks' ],
	},
	{
		name: 'postList',
		title: __( 'Post List', 'enable-navigation-icons' ),
		icon: postList,
		categories: [ 'blocks' ],
	},
	{
		name: 'postTerms',
		title: __( 'Post Terms', 'enable-navigation-icons' ),
		icon: postTerms,
		categories: [ 'blocks' ],
	},
	{
		name: 'previous',
		title: __( 'Previous', 'enable-navigation-icons' ),
		icon: previous,
		categories: [ 'arrows' ],
	},
	{
		name: 'next',
		title: __( 'Next', 'enable-navigation-icons' ),
		icon: next,
		categories: [ 'arrows' ],
	},
	{
		name: 'preformatted',
		title: __( 'Preformatted', 'enable-navigation-icons' ),
		icon: preformatted,
	},
	{
		name: 'pullLeft',
		title: __( 'Pull Left', 'enable-navigation-icons' ),
		icon: pullLeft,
	},
	{
		name: 'pullRight',
		title: __( 'Pull Right', 'enable-navigation-icons' ),
		icon: pullRight,
	},
	{
		name: 'pullquote',
		title: __( 'Pull Quote', 'enable-navigation-icons' ),
		icon: pullquote,
	},
	{
		name: 'queryPagination',
		title: __( 'Query Pagination', 'enable-navigation-icons' ),
		icon: queryPagination,
	},
	{
		name: 'queryPaginationNext',
		title: __( 'Query Pagination Next', 'enable-navigation-icons' ),
		icon: queryPaginationNext,
		categories: [ 'arrows' ],
	},
	{
		name: 'queryPaginationNumbers',
		title: __( 'Query Pagination Numbers', 'enable-navigation-icons' ),
		icon: queryPaginationNumbers,
	},
	{
		name: 'queryPaginationPrevious',
		title: __( 'Query Pagination Previous', 'enable-navigation-icons' ),
		icon: queryPaginationPrevious,
		categories: [ 'arrows' ],
	},
	{
		name: 'quote',
		title: __( 'Quote', 'enable-navigation-icons' ),
		icon: quote,
		categories: [ 'blocks' ],
	},
	{
		name: 'receipt',
		title: __( 'Receipt', 'enable-navigation-icons' ),
		icon: receipt,
	},
	{
		name: 'redo',
		title: __( 'Redo', 'enable-navigation-icons' ),
		icon: redo,
		categories: [ 'arrows', 'editor' ],
	},
	{
		name: 'removeBug',
		title: __( 'Remove Bug', 'enable-navigation-icons' ),
		icon: removeBug,
	},
	{
		name: 'removeSubmenu',
		title: __( 'Remove Submenu', 'enable-navigation-icons' ),
		icon: removeSubmenu,
	},
	{
		name: 'replace',
		title: __( 'Replace', 'enable-navigation-icons' ),
		icon: replace,
		categories: [ 'arrows' ],
	},
	{
		name: 'reset',
		title: __( 'Reset', 'enable-navigation-icons' ),
		icon: reset,
		keywords: [ 'minus' ],
	},
	{
		name: 'resizeCornerNE',
		title: __( 'Resize Corner', 'enable-navigation-icons' ),
		icon: resizeCornerNE,
		categories: [ 'arrows' ],
	},
	{
		name: 'reusableBlock',
		title: __( 'Reusable Block', 'enable-navigation-icons' ),
		icon: reusableBlock,
		categories: [ 'arrows' ],
	},
	{
		name: 'rotateLeft',
		title: __( 'Rotate Left', 'enable-navigation-icons' ),
		icon: rotateLeft,
		categories: [ 'arrows' ],
	},
	{
		name: 'rotateRight',
		title: __( 'Rotate Right', 'enable-navigation-icons' ),
		icon: rotateRight,
		categories: [ 'arrows' ],
	},
	{
		name: 'row',
		title: __( 'Row', 'enable-navigation-icons' ),
		icon: row,
	},
	{
		name: 'rss',
		title: __( 'RSS', 'enable-navigation-icons' ),
		icon: rss,
	},
	{
		name: 'search',
		title: __( 'Search', 'enable-navigation-icons' ),
		icon: search,
		keywords: [ 'magnifying glass' ],
	},
	{
		name: 'seen',
		title: __( 'Seen', 'enable-navigation-icons' ),
		icon: seen,
		keywords: [ 'eye', 'visible' ],
	},
	{
		name: 'separator',
		title: __( 'Separator', 'enable-navigation-icons' ),
		icon: separator,
		categories: [ 'blocks' ],
	},
	{
		name: 'settings',
		title: __( 'Settings', 'enable-navigation-icons' ),
		icon: settings,
	},
	{
		name: 'shadow',
		title: __( 'Shadow', 'enable-navigation-icons' ),
		icon: shadow,
		keywords: [ 'sun' ],
	},
	{
		name: 'share',
		title: __( 'Share', 'enable-navigation-icons' ),
		icon: share,
	},
	{
		name: 'shield',
		title: __( 'Shield', 'enable-navigation-icons' ),
		icon: shield,
	},
	{
		name: 'shortcode',
		title: __( 'Shortcode', 'enable-navigation-icons' ),
		icon: shortcode,
		categories: [ 'blocks' ],
	},
	{
		name: 'shuffle',
		title: __( 'Shuffle', 'enable-navigation-icons' ),
		icon: shuffle,
	},
	{
		name: 'siteLogo',
		title: __( 'Site Logo', 'enable-navigation-icons' ),
		icon: siteLogo,
		categories: [ 'blocks', 'media' ],
	},
	{
		isDefault: true,
		name: 'sparkles',
		title: __( 'Sparkles', 'enable-navigation-icons' ),
		icon: sparkles,
	},
	{
		name: 'stack',
		title: __( 'Stack', 'enable-navigation-icons' ),
		icon: stack,
	},
	{
		name: 'starEmpty',
		title: __( 'Star Empty', 'enable-navigation-icons' ),
		icon: starEmpty,
	},
	{
		name: 'starFilled',
		title: __( 'Star Filled', 'enable-navigation-icons' ),
		icon: starFilled,
	},
	{
		name: 'starHalf',
		title: __( 'Star Half', 'enable-navigation-icons' ),
		icon: starHalf,
	},
	{
		name: 'store',
		title: __( 'Store', 'enable-navigation-icons' ),
		icon: store,
	},
	{
		name: 'stretchFullWidth',
		title: __( 'Stretch Full Width', 'enable-navigation-icons' ),
		icon: stretchFullWidth,
		categories: [ 'editor' ],
	},
	{
		name: 'styles',
		title: __( 'Styles', 'enable-navigation-icons' ),
		icon: styles,
	},
	{
		isDefault: true,
		name: 'shipping',
		title: __( 'Shipping', 'enable-navigation-icons' ),
		icon: shipping,
		keywords: [ 'truck' ],
	},
	{
		name: 'stretchWide',
		title: __( 'Stretch Wide', 'enable-navigation-icons' ),
		icon: stretchWide,
		categories: [ 'editor' ],
	},
	{
		name: 'subscript',
		title: __( 'Subscript', 'enable-navigation-icons' ),
		icon: subscript,
		categories: [ 'editor' ],
	},
	{
		name: 'superscript',
		title: __( 'Superscript', 'enable-navigation-icons' ),
		icon: superscript,
		categories: [ 'editor' ],
	},
	{
		name: 'swatch',
		title: __( 'Swatch', 'enable-navigation-icons' ),
		icon: swatch,
	},
	{
		name: 'symbol',
		title: __( 'Symbol', 'enable-navigation-icons' ),
		icon: symbol,
	},
	{
		name: 'symbolFilled',
		title: __( 'Symbol - Filled', 'enable-navigation-icons' ),
		icon: symbolFilled,
	},
	{
		name: 'tableColumnAfter',
		title: __( 'Table Column After', 'enable-navigation-icons' ),
		icon: tableColumnAfter,
		categories: [ 'editor' ],
	},
	{
		name: 'tableColumnBefore',
		title: __( 'Table Column Before', 'enable-navigation-icons' ),
		icon: tableColumnBefore,
		categories: [ 'editor' ],
	},
	{
		name: 'tableColumnDelete',
		title: __( 'Table Column Delete', 'enable-navigation-icons' ),
		icon: tableColumnDelete,
		categories: [ 'editor' ],
	},
	{
		name: 'tableRowAfter',
		title: __( 'Table Row After', 'enable-navigation-icons' ),
		icon: tableRowAfter,
		categories: [ 'editor' ],
	},
	{
		name: 'tableRowBefore',
		title: __( 'Table Row Before', 'enable-navigation-icons' ),
		icon: tableRowBefore,
		categories: [ 'editor' ],
	},
	{
		name: 'tableRowDelete',
		title: __( 'Table Row Delete', 'enable-navigation-icons' ),
		icon: tableRowDelete,
		categories: [ 'editor' ],
	},
	{
		name: 'table',
		title: __( 'Table', 'enable-navigation-icons' ),
		icon: table,
	},
	{
		name: 'tag',
		title: __( 'Tag', 'enable-navigation-icons' ),
		icon: tag,
	},
	{
		name: 'termDescription',
		title: __( 'Term Description', 'enable-navigation-icons' ),
		icon: termDescription,
		categories: [ 'blocks' ],
	},
	{
		name: 'footer',
		title: __( 'Footer', 'enable-navigation-icons' ),
		icon: footer,
	},
	{
		name: 'header',
		title: __( 'Header', 'enable-navigation-icons' ),
		icon: header,
	},
	{
		name: 'sidebar',
		title: __( 'Sidebar', 'enable-navigation-icons' ),
		icon: sidebar,
	},
	{
		name: 'textColor',
		title: __( 'Text Color', 'enable-navigation-icons' ),
		icon: textColor,
	},
	{
		name: 'tablet',
		title: __( 'Tablet', 'enable-navigation-icons' ),
		icon: tablet,
		categories: [ 'devices' ],
	},
	{
		name: 'title',
		title: __( 'Title', 'enable-navigation-icons' ),
		icon: title,
	},
	{
		name: 'tip',
		title: __( 'Tip', 'enable-navigation-icons' ),
		icon: tip,
	},
	{
		name: 'tool',
		title: __( 'Tool', 'enable-navigation-icons' ),
		icon: tool,
	},
	{
		name: 'trash',
		title: __( 'Trash', 'enable-navigation-icons' ),
		icon: trash,
	},
	{
		name: 'trendingDown',
		title: __( 'Trending Down', 'enable-navigation-icons' ),
		icon: trendingDown,
		categories: [ 'arrows' ],
	},
	{
		name: 'trendingUp',
		title: __( 'Trending Up', 'enable-navigation-icons' ),
		icon: trendingUp,
		categories: [ 'arrows' ],
	},
	{
		name: 'typography',
		title: __( 'Typography', 'enable-navigation-icons' ),
		icon: typography,
	},
	{
		name: 'undo',
		title: __( 'Undo', 'enable-navigation-icons' ),
		icon: undo,
		categories: [ 'arrows', 'editor' ],
	},
	{
		name: 'ungroup',
		title: __( 'Ungroup', 'enable-navigation-icons' ),
		icon: ungroup,
		categories: [ 'editor' ],
	},
	{
		name: 'unlock',
		title: __( 'Unlock', 'enable-navigation-icons' ),
		icon: unlock,
		categories: [ 'editor' ],
	},
	{
		name: 'unseen',
		title: __( 'Unseen', 'enable-navigation-icons' ),
		icon: unseen,
		keywords: [ 'eye', 'hidden' ],
	},
	{
		name: 'update',
		title: __( 'Update', 'enable-navigation-icons' ),
		icon: update,
	},
	{
		name: 'upload',
		title: __( 'Upload', 'enable-navigation-icons' ),
		icon: upload,
		categories: [ 'arrows' ],
	},
	{
		isDefault: true,
		name: 'verse',
		title: __( 'Verse', 'enable-navigation-icons' ),
		icon: verse,
		categories: [ 'blocks' ],
	},
	{
		name: 'video',
		title: __( 'Video', 'enable-navigation-icons' ),
		icon: video,
		categories: [ 'media' ],
	},
	{
		name: 'warning',
		title: __( 'Warning', 'enable-navigation-icons' ),
		icon: warning,
	},
	{
		name: 'widget',
		title: __( 'Widget', 'enable-navigation-icons' ),
		icon: widget,
	},
];

const icons = [
	{
		isDefault: false,
		type: 'wordpress',
		title: __( 'WordPress', 'enable-navigation-icons' ),
		icons: [].concat( wordpressSocialIcons, wordpressIcons ),
		categories: [
			{
				name: 'arrows',
				title: __( 'Arrows', 'enable-navigation-icons' ),
			},
			{
				name: 'blocks',
				title: __( 'Blocks', 'enable-navigation-icons' ),
			},
			{
				name: 'devices',
				title: __( 'Devices', 'enable-navigation-icons' ),
			},
			{
				name: 'editor',
				title: __( 'Editor', 'enable-navigation-icons' ),
			},
			{
				name: 'logos',
				title: __( 'Logos', 'enable-navigation-icons' ),
			},
			{
				name: 'media',
				title: __( 'Media', 'enable-navigation-icons' ),
			},
		],
	},
];

// Allow third parties to add their own icon types via filter.
export default function getIcons() {
	return applyFilters( 'iconBlock.icons', icons );
}
